### PR TITLE
Using Themekit V1

### LINKED ISSUE #33: How should I update themekit
### Problem

Currently I am getting a warning that there is an update for themekit but there is no update for node-themekit. 

How should I go about updating the dependancy?

Thanks
D

### LINKED ISSUE #34: themekit.command does not reject promises on error
### Problem

node-themekit's `command` function does not throw any JS errors or reject the promise it returns if it runs into exceptions.

### Replication steps

- Run into error during a command (You can do this by deleting a file that is supposed to be `deploy`ed, or having bad store credentials, or bad theme id)
- themekit will output an error message to the terminal after finishing the command
- themekit will not throw any errors, reject the promise, or return anything useful

Reduced test case:

```js
const themeKit = require('@shopify/themekit'); // @1.0.1

themeKit
  .command(
    'deploy',
    {
      store: `anything.myshopify.com`,
      password: 'anything',
    },
    {
      cwd: './Timber',
      logLevel: 'all',
    }
  )
  .then(res => console.log('Result', res))
  .catch(err => console.error('Error', err));

// Output:
// invalid environment [development]: (invalid theme_id)
// Result undefined

```

### Additional Info

I see there are similar issues (#14 and #19) that were addressed by #23. I am on v1.0.1 but am still seeing problems with error handling.

### PR DESCRIPTION
**Pull request by harshal317**
### What are you trying to accomplish with this PR?

Updates node-themekit to using themekit 1.0.0, fixes #33 and fixes #34 
I have tested to make sure these commands (https://shopify.github.io/themekit/commands/) work 

Major change was that flags weren't in kebab case and were all just lowercase, I am unsure what the previous flags that were supported by the wrapper were, but this solution should support all the flags listed in the themekit documentation

### CODE REVIEW

File: __tests__/utils.js [hunk 1]
```diff
@@ -34,9 +34,14 @@ describe('getFlagArrayFromObject', () => {
 
   test('correctly deconstructs ignoredFiles flag', () => {
     const input = {
-      ignoredFiles: ['file1', 'file2']
+      ignoredFile: ['file1', 'file2']
```
Comment (t-kelly) [inline __tests__/utils.js]: `ignoredFiles` has changed to `ignoredFile`? If so thats a breaking change. Can we keep it `ignoredFiles`?

File: lib/utils.js [hunk 2]
```diff
@@ -25,12 +25,16 @@ function cleanFile(pathToFile) {
  */
 function getFlagArrayFromObject(obj) {
   return Object.keys(obj).reduce((arr, key) => {
-    const flag = `--${_kebabCase(key)}`;
-    if (typeof obj[key] === 'boolean') {
+    const flag = `--${key.toLowerCase()}`;
+    if (key === 'noUpdateNotifier' && typeof obj[key] === 'boolean') {
```
Comment (t-kelly) [inline lib/utils.js]: Would you mind explaining this change?

Comment (harshal317) [reply lib/utils.js]: All the documented flags are lowercase no spaces/dashes except --ignored-file. noUpdateNotifier isn't documented in themekit but we use it to prevent the node-themekit users from getting a warning to update themekit, and it is still a kebab case flag so separate case for that.

File: __tests__/utils.js (hunk 1 above)
Comment (harshal317) [reply __tests__/utils.js]: The themekit flag is --ignored-file and our node-themekit documentation says

> All flags specified in the Theme Kit documentation are available, but in camelCase rather than in --flag-form

We can make it ignoredFiles again but then we'd have to start making a list of exceptions as to which flags arent exactly the camelCase version of the themekit docs which doesn't seem ideal

Comment (t-kelly) [reply __tests__/utils.js]: Okay, I like your logic -- we'll just need to do a major version bump since this is breaking.

**Comment by harshal317** [comment]
> Looking good! One small change and then I'll give it a 🎩.
> 
> > I am unsure what the previous flags that were supported by the wrapper were, but this solution should support all the flags listed in the themekit documentation
> 
> Maybe we could create some new tests (maybe even snapshot tests?) for `lib/themekit.js` which tests the public API users will interface with? Test each flag and variation of input?

👍 Pushed tests

**Comment by harshal317** [comment]
Latest push fixes #34

File: __tests__/themekit.js [hunk 3]
```diff
@@ -0,0 +1,341 @@
...
+
+  test('deploy all environments no delete', async () => {
+    const {spawn} = require('child_process');
+
+    const pathToExecutable = path.join(cfg.destination, cfg.binName);
+    const cwd = process.cwd();
+
+    await themekit.command('deploy', {
+      allenvs: true,
+      nodelete: true
```
Comment (t-kelly) [inline __tests__/themekit.js]: Should these be camelcase?

File: __tests__/themekit.js [hunk 4]
```diff
@@ -0,0 +1,341 @@
...
+const themekit = require('../lib/themekit');
+
+jest.mock('child_process');
+
+describe('themekit', () => {
+  test('configure', async () => {
+    const {spawn} = require('child_process');
+
+    const pathToExecutable = path.join(cfg.destination, cfg.binName);
+    const cwd = process.cwd();
```
[the remark this answers is not in the document]
Comment (harshal317) [reply __tests__/themekit.js]: 👍

File: __tests__/themekit.js (hunk 3 above)
Comment (harshal317) [reply __tests__/themekit.js]: Yes my mistake, good eye

**Comment by harshal317** [comment]
> I think we should be able to do this without a major version bump. Lets try and remain as backwards compatible as possible.

Since ignoredFile is all that changed, we can add a catch to support ignoredFiles as well

**Comment by harshal317** [comment]
Latest commit makes it backwards compatible to the best of my knowledge

File: lib/utils.js [hunk 5]
```diff
@@ -30,7 +30,7 @@ function getFlagArrayFromObject(obj) {
       return obj[key] ? [...arr, '--no-update-notifier'] : arr;
     } else if (typeof obj[key] === 'boolean') {
       return obj[key] ? [...arr, flag] : arr;
-    } else if (key === 'ignoredFile') {
+    } else if (key === 'ignoredFile' || key === 'ignoredFiles') {
```
Comment (t-kelly) [inline lib/utils.js]: Won't this break if ignoredFile is just a single string?

File: __tests__/themekit.js [hunk 6]
```diff
@@ -69,6 +69,28 @@ describe('themekit', () => {
     );
   });
 
+  test('deploy ignore files old themekit', async () => {
+    await themekit.command('deploy', {
+      ignoredFiles: ['templates/404.liquid', 'templates/article.liquid']
+    });
```
Comment (t-kelly) [inline __tests__/themekit.js]: You could also test `ignoredFile` here: 
```
ignoredFile: 'templates/product.liquid'
```

File: lib/utils.js (hunk 5 above)
Comment (harshal317) [reply lib/utils.js]: Ok so after looking at how we document ignoring files in node-themekit, I realized I overlooked that ignoredFiles was an additional flag that we added on the wrapper. So I kept ignoredFiles to only support arrays, and ignored-file since its kebab case unlike most, I added a case for. I also removed ignoredFile allowing an array as its unintuitive especially when we have the additional ignoredFiles flag

File: __tests__/themekit.js (hunk 6 above)
Comment (harshal317) [reply __tests__/themekit.js]: 👍

**Comment by harshal317** [comment]
> Looks good! So just to confirm, we have no breaking changes in the PR?

Yep

**Comment by t-kelly** [comment]
🚢
